apiVersion: v1
kind: ConfigMap
metadata:
  name: avnu-config
data:
  redis-host: "redis-master.redis.svc.cluster.local"
  redis-port: "6379"
  elasticsearch-url: "http://elasticsearch-master.elasticsearch.svc.cluster.local:9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: avnu-db-credentials
type: Opaque
data:
  host: cG9zdGdyZXMtaGEucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw= # postgres-ha.postgres.svc.cluster.local
  port: NTQzMg== # 5432
  username: YXZudQ== # avnu
  password: Y2hhbmdlbWU= # changeme
  database: YXZudV9kYg== # avnu_db
---
apiVersion: v1
kind: Secret
metadata:
  name: avnu-es-credentials
type: Opaque
data:
  username: ZWxhc3RpYw== # elastic
  password: Y2hhbmdlbWU= # changeme
