services:
  # Backend API Service
  - type: web
    name: avnu-marketplace-api
    env: node
    rootDir: backend
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      # Add other environment variables as needed
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: avnu-marketplace-db
      #     property: connectionString
      # - key: ELASTICSEARCH_NODE
      #   value: https://your-elasticsearch-instance.com

  # Optional: Frontend Service (if you want to deploy frontend separately from Vercel)
  # - type: web
  #   name: avnu-marketplace-frontend
  #   env: node
  #   rootDir: frontend
  #   buildCommand: npm install && npm run build
  #   startCommand: npm run start
  #   envVars:
  #     - key: NEXT_PUBLIC_API_URL
  #       value: https://avnu-marketplace-api.onrender.com

# Optional: Database Service
# databases:
#   - name: avnu-marketplace-db
#     plan: starter
