name: CI

# Run on every push to main/staging and on every pull-request
on:
  push:
    branches: [main, staging]
  pull_request:
    branches: ['**']

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - uses: actions/checkout@v4

    # 2. Set up Node (uses caching automatically)
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    # 3. Install deps
    - run: npm ci

    # 4. Lint (keep code style consistent)
    - run: npm run lint

    # 5. Type-check (catches TS errors)
    - run: npm run typecheck

    # 6. Run unit tests
    - run: npm test -- --runInBand

    # 7. Build the production bundle (optional but nice to catch build-time errors)
    - run: npm run build
