name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure npm cache directory exists
        run: mkdir -p ~/.npm

      - name: Ensure npm cache directory exists
        run: mkdir -p ~/.npm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run tests
        run: |
          cd backend
          npm test
          
  deploy-render:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key:   ${{ secrets.RENDER_API_KEY }}
