name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, worker]
        include:
          - service: frontend
            dockerfile: frontend/Dockerfile
            image: avnu-marketplace-web
            build_context: .
          - service: backend
            dockerfile: backend/Dockerfile
            image: avnu-marketplace-api
            build_context: .
          - service: worker
            dockerfile: backend/Dockerfile.worker
            image: avnu-marketplace-worker
            build_context: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.build_context }} # Changed from .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}

      - name: Notify success
        if: success()
        run: |
          echo "✅ Successfully built and pushed ${{ matrix.service }} Docker image"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }}"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Failed to build or push ${{ matrix.service }} Docker image"
