name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Ensure npm cache directory exists
        run: mkdir -p ~/.npm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: |
          echo "better-sqlite3_binary=true" >> .npmrc
          echo "sqlite3_binary=true" >> .npmrc
          # Create .npmrc with relaxed settings
          echo "better-sqlite3_binary=true" > .npmrc
          echo "sqlite3_binary=true" >> .npmrc
          echo "multer@=\"2.0.1\"" >> .npmrc
          echo "legacy-peer-deps=true" >> .npmrc
          echo "engine-strict=false" >> .npmrc
          echo "package-lock=false" >> .npmrc
          echo "force=true" >> .npmrc
          
          # Install dependencies with force flag
          npm install --force --no-package-lock --no-audit --no-fund
        
      - name: Run ESLint
        run: npm run lint

  lint-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Ensure npm cache directory exists
        run: mkdir -p ~/.npm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      
      - name: Install dependencies
        run: |
          echo "better-sqlite3_binary=true" >> .npmrc
          echo "sqlite3_binary=true" >> .npmrc
          # Create .npmrc with relaxed settings
          echo "better-sqlite3_binary=true" > .npmrc
          echo "sqlite3_binary=true" >> .npmrc
          echo "multer@=\"2.0.1\"" >> .npmrc
          echo "legacy-peer-deps=true" >> .npmrc
          echo "engine-strict=false" >> .npmrc
          echo "package-lock=false" >> .npmrc
          echo "force=true" >> .npmrc
          
          # Install dependencies with force flag
          npm install --force --no-package-lock --no-audit --no-fund
        
      - name: Run ESLint
        run: cd backend && npm run lint
