name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday

jobs:
  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Run npm audit (backend)
        working-directory: ./backend
        run: npm audit --production --audit-level=high

      - name: Run npm audit (frontend)
        working-directory: ./frontend
        run: npm audit --production --audit-level=high

  code-scanning:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Build
        run: |
          # Create .npmrc with relaxed settings
          echo "better-sqlite3_binary=true" > .npmrc
          echo "sqlite3_binary=true" >> .npmrc
          echo "multer@=\"2.0.1\"" >> .npmrc
          echo "legacy-peer-deps=true" >> .npmrc
          echo "engine-strict=false" >> .npmrc
          echo "package-lock=false" >> .npmrc
          echo "force=true" >> .npmrc
          
          # Install dependencies with force flag
          npm install --force --no-package-lock --no-audit --no-fund
          npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.31.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
